name    'BoxUpp-apache_maven'
version '0.0.6'
source 'UNKNOWN'
author 'BoxUpp'
license 'Apache License, Version 2.0'
summary 'A puppet module to install apache maven'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
