name    'BoxUpp/haproxy1'
version '0.0.2'
source 'UNKNOWN'
author 'BoxUpp'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
